---
- hosts: all

  tasks:
  - name: install example application
    copy: 
      src: ansible_test_app 
      dest: /tmp/
      owner: root
      group: root

  - name: "GET_URL | Download MINIO server"
    get_url:
      #url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2023-10-25T06-33-25Z
      url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2023-10-16T04-13-43Z
      dest: /usr/local/bin/minio
      mode: 0755
      timeout: 30
