---
- hosts: all

  tasks:
  - name: install example application
    copy: 
      src: ansible_test_app 
      dest: /tmp/
      owner: root
      group: root

  - name: "Set minio version"
    set_fact:
      miniov: 'minio.RELEASE.2023-10-25T06-33-25Z'

  - name: "GET_URL | Get minio checksum"
    get_url:
      url: https://dl.min.io/server/minio/release/linux-amd64/archive/{{ miniov }}.sha256sum
      dest: /tmp/{{ miniov }}.sha256sum
    
  - name: "GET_URL | Download MINIO server"
    get_url:
      url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2023-10-25T06-33-25Z
      dest: /usr/local/bin/minio
      checksum: sha256:https://dl.min.io/server/minio/release/linux-amd64/archive/{{ miniov }}.sha256sum
      mode: 0755
      timeout: 30
