---
- hosts: all

  tasks:
 
  - name: "Set minio version"
    set_fact:
      miniov: 'minio.RELEASE.2023-10-16T04-13-43Z'

  - name: "GET URI | GET MINIO CHECKSUM"
    uri:
      url: https://dl.min.io/server/minio/release/linux-amd64/archive/{{ miniov }}.sha256sum
      return_content: true
    register: url_sha256
    
  - name: "Set URL_CHECKSUM"
    set_fact:
      minio_checksum: "{{ url_sha256.content.split(' ')[0] }}" 
  
  - name: "GET_URL | Download MINIO server"
    get_url:
      url: https://dl.min.io/server/minio/release/linux-amd64/archive/{{ miniov }}
      checksum: "sha256:{{ minio_checksum }}"
      dest: /usr/local/bin/minio
      mode: 0755
      timeout: 30
